import java.util.*;
import java.io.*;

public class textarray {
	// Program: Converting a text file to an array, Programming Exercise 5
	// File: ProgrammingExercise5.java
	// Summary: Reads text from an input file and stores it in an array
	// Author: Christopher A Lambert
	// Date: 11/12/2017

	public static void main(String[] args) throws IOException { // main method
		File inputtext = new File("/inputtext.txt"); //Reads my file from C://inputtext.txt
		Split(inputtext); // SUPPOSED to split the input text into separate characters but it doesn't seem to work
		Scanner text = new Scanner(inputtext);// Creates a scanner to analyze the read file

		char[] fullarray = new char[20 * 45];//creates the array with a fixed size of 20x45
		int maxlimit = 0;
		while (text.hasNext()) {// checks to see for actual characters to store in the array instead of spaces
			char[] initialarray = text.nextLine().toCharArray();
			maxlimit += initialarray.length;
			if (maxlimit <= fullarray.length) { //if/else check for the requirement to ignore excess characters, this seems to work.
				System.arraycopy(initialarray, 0, fullarray, 0, initialarray.length);
			} else {
				System.arraycopy(initialarray, 0, fullarray, 0, initialarray.length - (maxlimit - fullarray.length));
			}
		}

		if (!text.hasNext()) {//this checks for spaces to be replaced with an @, this does not work.
			for (int space = fullarray.length - 1; space >= maxlimit; space--) {
				fullarray[space] = '@';
			}
		}
		text.close();
		String finaloutput = "";
		int list = 0;
		char[][] outputarray = new char[20][45]; //converts the fixed array to an arraylist to be output 
		for (int x = 0; x < outputarray.length; x++) { // using the finaloutput string
			for (int y = 0; y < outputarray[x].length; y++) {
				if (list < fullarray.length) {
					outputarray[x][y] = fullarray[list];
					list++;
					finaloutput += outputarray[x][y];
					System.out.println(finaloutput);// Outputs the final text to the console
				}
			}
		}
	}

	private static void Split(File inputtext) {
		// TODO Auto-generated method stub (This was created by Eclipse to fix an error
		// generated by my Split command line, no idea why it decided to place it down here)
	}	// I'm not exactly certain what my output is supposed to look like, but it's not like how it looks in this program.
		// The split doesn't seem to function as I assumed it would so the array isn't getting split into individual characters
}